// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.747
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"github.com/kevin07696/ecommerce/templates/layouts"
	"github.com/kevin07696/ecommerce/templates/models"
	"github.com/kevin07696/ecommerce/templates/partials"
)

func RegisterForm() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Var3 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
				templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
				templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
				if !templ_7745c5c3_IsBuffer {
					defer func() {
						templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
						if templ_7745c5c3_Err == nil {
							templ_7745c5c3_Err = templ_7745c5c3_BufErr
						}
					}()
				}
				ctx = templ.InitializeContext(ctx)
				templ_7745c5c3_Var4 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
					templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
					templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
					if !templ_7745c5c3_IsBuffer {
						defer func() {
							templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
							if templ_7745c5c3_Err == nil {
								templ_7745c5c3_Err = templ_7745c5c3_BufErr
							}
						}()
					}
					ctx = templ.InitializeContext(ctx)
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"box-border border-2 border-solid border-white p-4 text-white\"><form id=\"register\" class=\"flex flex-col gap-2\" enctype=\"application/x-www-form-urlencoded\" hx-post=\"/api/register\" hx-swap=\"innerHTML\" hx-target=\"#response\" hx-target-*=\"#error\">")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = partials.DefaultInput("register", "bg-slate-700", models.NewInput("email", "email", "Email",
						models.WithFill("email"),
						models.WithRequired(),
						models.WithFocus(),
						models.WithInpTyp("email"),
						models.WithPlace("username+sub@domain.sub.tld"),
						models.WithPattern(`^[\w.]+[+\-]?[\w.]*@[\w]+[.][\w]+[.]?[\w]*$`),
						models.WithButton("Send OTP",
							models.WithBtnRequest(
								models.WithParams("email"),
								models.WithRequest("POST", "/api/valid-email"),
								models.WithSwap("innerHTML"),
								models.WithTarget("#email-error")),
							models.WithBtnTempl("solid-rounded"),
							models.WithBtnStyle("active:box-border hover:bg-slate-400 active:bg-slate-600 active:text-white"),
						),
						models.WithHint(`*Email should only contain letters, numbers, periods ('.'), or underscores ('_').`),
					)).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = partials.DefaultInput("register", "bg-slate-700", models.NewInput("otp", "otp", "One Time Password",
						models.WithPlace("12345678"),
						models.WithRequired(),
						models.WithPattern(".{8}"),
					)).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = partials.DefaultInput("register", "bg-slate-700", models.NewInput("username", "username", "Username",
						models.WithFill("username"),
						models.WithRequired(),
						models.WithFocus(),
						models.WithInpTyp("text"),
						models.WithPlace("username"),
						models.WithPattern(`^[a-zA-Z][a-zA-Z0-9_]{3,19}$`),
						models.WithButton("Check Availability",
							models.WithBtnRequest(
								models.WithParams("username"),
								models.WithRequest("GET", "/api/valid-username"),
								models.WithSwap("innerHTML"),
								models.WithTarget("#username-error")),
							models.WithBtnTempl("solid-rounded"),
							models.WithBtnStyle("active:box-border hover:bg-slate-400 active:bg-slate-600 active:text-white"),
						),
						models.WithHint(`*Username should be between 4-19 characters long, and only contain letters, numbers, or underscores ('_').`),
					)).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = partials.DefaultInput("register", "bg-slate-700", models.NewInput("role", "role", "Role",
						models.WithPlace("Role"),
						models.WithRequired(),
						models.WithPattern(".*"))).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					templ_7745c5c3_Err = partials.Basic("register", models.NewButton("Register", models.WithBtnStyle("hover:bg-slate-600 active:bg-slate-700"))).Render(ctx, templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<p id=\"response\" class=\"text-sm\"></p><p id=\"error\" class=\"text-sm\"></p></form></div>")
					if templ_7745c5c3_Err != nil {
						return templ_7745c5c3_Err
					}
					return templ_7745c5c3_Err
				})
				templ_7745c5c3_Err = layouts.GridMiddle().Render(templ.WithChildren(ctx, templ_7745c5c3_Var4), templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err != nil {
					return templ_7745c5c3_Err
				}
				return templ_7745c5c3_Err
			})
			templ_7745c5c3_Err = layouts.Grid("bg-slate-700").Render(templ.WithChildren(ctx, templ_7745c5c3_Var3), templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return templ_7745c5c3_Err
		})
		templ_7745c5c3_Err = layouts.Start("Register").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}
